### PR TITLE
2.0/Merge from develop 1.0

### PR DESCRIPTION
**Pull request by baseTwo**
ℹ️Work for issue #325 

Merged from develop 1.0 branch into develop 2.0

### CODE REVIEW

**Comment by ewoutkramer** [comment]
Whoaaa.....this is 2.0 into 1.0 ;-)

Merging 1.0 into 2.0 should be simple, since I do that periodically, should not be this many files ;-)

**Comment by ewoutkramer** [comment]
Assuming this was a mistake.

**Comment by baseTwo** [comment]
> Assuming this was a mistake.

Only the base was incorrect. Changed it to develop-2.0 and re-opened.

**Comment by ewoutkramer** [comment]
This makes sense to me, yes, looks like the changes I have seen PRs for on 1.0.

**Comment by baseTwo** [comment]
Replaced by new PR #370

**Pull request closed without merging**
